/*
    This component is displayed in the PracticeHubPage on the left for the reminder function.
*/
pragma ComponentBehavior: Bound

import QtQuick
import QtQuick.Controls
import QtQuick.Layouts
import QtCore

import "."

Rectangle {
    id: root

    // ── Required properties ───────────────────────────────────────────────
    required property int    songId
    required property string songTitle
    required property string groupTitle
    required property int    practiceAssetId

    // ── Media labels (one per kind, set by PracticeHubPage) ──────────────
    property string guitarProLabel: ""
    property string audioLabel:     ""
    property string videoLabel:     ""
    property string imageLabel:     ""
    property string documentLabel:  ""
    property bool _titleIsAutoGenerated: true

    // ── Signals ───────────────────────────────────────────────────────────
    signal openCalendarRequested
    signal commitAssetRequested()

    // ── Panel state ───────────────────────────────────────────────────────
    property bool panelEnabled:      true
    property bool expanded:          true
    property int  editingReminderId: 0
    property var  reminderStartDate: new Date()
    property var  reminderViewDate:  new Date(new Date().getFullYear(), new Date().getMonth(), 1)

    readonly property int expandedWidth:  280
    readonly property int collapsedWidth: 44

    readonly property bool conditionInputValid:
    condStartBar.value > 0 &&
    condEndBar.value >= condStartBar.value &&
    condMinBpm.value > 0 &&
    condMinMinutes.value >= 0

    readonly property bool hasMediaSelection:
    root.guitarProLabel.length > 0 ||
    root.audioLabel.length     > 0 ||
    root.videoLabel.length     > 0 ||
    root.imageLabel.length     > 0 ||
    root.documentLabel.length  > 0

    // ── Layout ────────────────────────────────────────────────────────────
    implicitWidth:        panelEnabled ? (expanded ? expandedWidth : collapsedWidth) : collapsedWidth
    Layout.preferredWidth: implicitWidth
    Layout.fillHeight:    true
    radius:               10
    color:                Theme.panelBackground
    border.color:         Theme.border

    // ── Persistent settings ───────────────────────────────────────────────
    Settings {
        id: panelPrefs
        location: appSettings.settingsFileLocation
        category: "ReminderPanel"
    }

    // ── Helper functions ──────────────────────────────────────────────────
    function toJsDate(value) {
        if (!value) return null;
        if (value instanceof Date) return value;
        if (value.year !== undefined)
            return new Date(value.year, value.month - 1, value.day);
        return null;
    }

    function selectedPracticeDate() {
        return toJsDate(practiceTracker.selectedDate) ?? new Date();
    }

    function reminderDateForSave() {
        return toJsDate(root.reminderStartDate) ?? new Date();
    }

    function resetReminderStartDate() {
        root.reminderStartDate = root.selectedPracticeDate();
        root.syncReminderViewToStart();
    }

    function syncReminderViewToStart() {
        const js = toJsDate(root.reminderStartDate);
        if (js)
            root.reminderViewDate = new Date(js.getFullYear(), js.getMonth(), 1);
    }

    function setReminderStartDate(date) {
        const js = toJsDate(date);
        if (!js)
            return;
        root.reminderStartDate = js;
        root.syncReminderViewToStart();
    }

    function shiftReminderMonth(delta) {
        root.reminderViewDate = new Date(root.reminderViewDate.getFullYear(),
                                         root.reminderViewDate.getMonth() + delta, 1);
    }

    function datesEqual(a, b) {
        const da = toJsDate(a);
        const db = toJsDate(b);
        if (!da || !db)
            return false;
        return da.getFullYear() === db.getFullYear()
                && da.getMonth() === db.getMonth()
                && da.getDate() === db.getDate();
    }

    function weekdayIndexFromDate(date) {
        const js = toJsDate(date);
        return js ? js.getDay() : new Date().getDay();
    }

    function scheduleIndexForType(scheduleType) {
        const values = ["once", "daily", "weekly", "monthly", "interval"];
        const idx = values.indexOf(scheduleType);
        return idx >= 0 ? idx : 0;
    }

    function _buildAutoTitle() {
        const base = root.groupTitle.length > 0 ? root.groupTitle : root.songTitle;
        const parts = [base];
        if (condStartBar.value > 0 && condEndBar.value >= condStartBar.value)
            parts.push(qsTr("Bar %1–%2").arg(condStartBar.value).arg(condEndBar.value));
        if (condMinBpm.value > 0)
            parts.push(qsTr("%1 BPM").arg(condMinBpm.value));
        return parts.join(" · ");
    }

    function _maybeSetAutoTitle() {
        if (!root._titleIsAutoGenerated)
            return;

        if (!root.hasMediaSelection) {
            titleField.text = "";
            return;
        }

        titleField.text = root._buildAutoTitle();
    }

    function applyTrainingDefaults() {
        if (root.editingReminderId > 0)
            return;
        condStartBar.value  = practiceTracker.startBar;
        condEndBar.value    = practiceTracker.endBar;
        condMinBpm.value    = practiceTracker.targetBpm;
        _maybeSetAutoTitle();
    }

    function loadReminderForEdit(reminderId) {
        const payload = reminderController.reminderEditPayload(reminderId);
        if (!payload || !payload.reminderId)
            return;
        saveExpanded(true);
        editingReminderId         = payload.reminderId;
        titleField.text           = payload.title ?? "";
        root._titleIsAutoGenerated = false;
        activeCheck.checked       = payload.isActive !== false;
        scheduleCombo.currentIndex = scheduleIndexForType(payload.scheduleType ?? "once");
        if (payload.reminderDate) {
            const rd = payload.reminderDate;
            if (rd.year !== undefined)
                root.setReminderStartDate(new Date(rd.year, rd.month - 1, rd.day));
            else
                root.setReminderStartDate(rd);
        }
        if (payload.weekday !== undefined && payload.weekday >= 0)
            weekdayRow.selectedWeekday = payload.weekday;
        else
            weekdayRow.selectedWeekday = root.weekdayIndexFromDate(root.reminderStartDate);
        if (payload.intervalDays !== undefined && payload.intervalDays > 0)
            intervalDaysSpin.value = payload.intervalDays;
        condStartBar.value        = payload.conditionStartBar   ?? 0;
        condEndBar.value          = payload.conditionEndBar     ?? 0;
        condMinBpm.value          = payload.conditionMinBpm     ?? 0;
        condMinMinutes.value      = payload.conditionMinMinutes ?? 0;
    }

    function prefsKey(suffix) {
        return suffix + "_" + root.songId + "_" + root.practiceAssetId;
    }

    function loadPrefs() {
        if (root.songId <= 0) {
            root.panelEnabled = true;
            root.expanded     = false;
            return;
        }
        root.panelEnabled = panelPrefs.value(prefsKey("visible"),  true);
        root.expanded     = panelPrefs.value(prefsKey("expanded"), false);
    }

    function saveExpanded(value) {
        if (root.songId <= 0) return;
        panelPrefs.setValue(prefsKey("expanded"), value);
        root.expanded = value;
    }

    function savePanelEnabled(value) {
        if (root.songId <= 0) return;
        panelPrefs.setValue(prefsKey("visible"), value);
        root.panelEnabled = value;
        if (!value) root.expanded = false;
    }

    // ── Reactive handlers ─────────────────────────────────────────────────
    onSongIdChanged: {
        loadPrefs();
        reminderController.songId = root.songId;
        applyTrainingDefaults();
    }

    onPracticeAssetIdChanged: {
        loadPrefs();
        reminderController.practiceAssetId = root.practiceAssetId;
        if (root.editingReminderId > 0)
        root.editingReminderId = 0;
        applyTrainingDefaults();
    }

    onEditingReminderIdChanged: {
        if (root.editingReminderId === 0)
        applyTrainingDefaults();
    }

    // Update auto-title when a media label changes
    onGuitarProLabelChanged: Qt.callLater(function() { _maybeSetAutoTitle() })
    onAudioLabelChanged:     Qt.callLater(function() { _maybeSetAutoTitle() })
    onVideoLabelChanged:     Qt.callLater(function() { _maybeSetAutoTitle() })
    onImageLabelChanged:     Qt.callLater(function() { _maybeSetAutoTitle() })
    onDocumentLabelChanged:  Qt.callLater(function() { _maybeSetAutoTitle() })

    Component.onCompleted: {
        loadPrefs();
        reminderController.songId          = root.songId;
        reminderController.practiceAssetId = root.practiceAssetId;
        root.resetReminderStartDate();
    }

    // ── Collapsed / disabled bar ──────────────────────────────────────────
    ColumnLayout {
        anchors.fill:    parent
        anchors.margins: 6
        spacing:         8
        visible:         !root.expanded || !root.panelEnabled

        ToolButton {
            id: expandButton
            Layout.alignment: Qt.AlignHCenter
            text: "›"
            ToolTip.visible: expandButton.hovered
            ToolTip.text:    root.panelEnabled ? qsTr("Expand reminder") : qsTr("Show reminder")
            onClicked: {
                if (!root.panelEnabled)
                root.savePanelEnabled(true);
                root.saveExpanded(true);
            }
        }

        Label {
            Layout.fillWidth:  true
            Layout.alignment:  Qt.AlignHCenter
            rotation:          -90
            text:              qsTr("Reminder")
            font.pixelSize:    11
            font.weight:       Font.DemiBold
            color:             Theme.accentLight
        }

        Item { Layout.fillHeight: true }
    }

    // ── Expanded content ──────────────────────────────────────────────────
    ColumnLayout {
        anchors.fill:    parent
        anchors.margins: 10
        spacing:         8
        visible:         root.expanded && root.panelEnabled

        // Header row
        RowLayout {
            Layout.fillWidth: true
            spacing: 4

            Label {
                Layout.fillWidth: true
                text:          qsTr("Reminder")
                font.pixelSize: 14
                font.weight:   Font.DemiBold
                color:         Theme.accentLight
            }

            ToolButton {
                id: collapseButton
                text: "‹"
                ToolTip.visible: collapseButton.hovered
                ToolTip.text:    qsTr("Collapse")
                onClicked: root.saveExpanded(false)
            }
        }

        // Calendar button
        Button {
            Layout.fillWidth: true
            text:    qsTr("Go to calendar")
            flat:    true
            onClicked: root.openCalendarRequested()
        }

        // Practice date (sync shortcut)
        Label {
            Layout.fillWidth: true
            wrapMode: Text.WordWrap
            text: {
                const sel = root.toJsDate(practiceTracker.selectedDate);
                return sel
                ? qsTr("Practice date: %1").arg(Qt.formatDate(sel, Qt.locale().dateFormat(Locale.ShortFormat)))
                : qsTr("Practice date: today");
            }
            font.pixelSize: 11
            color:          Theme.textSecondary
        }

        Button {
            Layout.fillWidth: true
            text:    qsTr("Use practice date as start")
            flat:    true
            font.pixelSize: 10
            onClicked: root.resetReminderStartDate()
        }

        Label {
            Layout.fillWidth: true
            text:           qsTr("Start date")
            font.pixelSize: 11
            font.weight:    Font.DemiBold
            color:          Theme.textSecondary
        }

        RowLayout {
            Layout.fillWidth: true
            spacing: 4

            ToolButton {
                text: qsTr("‹")
                onClicked: root.shiftReminderMonth(-1)
            }

            Label {
                Layout.fillWidth: true
                horizontalAlignment: Text.AlignHCenter
                text: Qt.formatDate(root.reminderViewDate, "MMMM yyyy")
                font.pixelSize: 11
                font.weight: Font.DemiBold
                color: Theme.textPrimary
            }

            ToolButton {
                text: qsTr("›")
                onClicked: root.shiftReminderMonth(1)
            }
        }

        MonthGrid {
            id: reminderMonthGrid
            Layout.fillWidth: true
            Layout.preferredHeight: 132
            month: root.reminderViewDate.getMonth()
            year: root.reminderViewDate.getFullYear()
            locale: Qt.locale()

            onClicked: (date) => root.setReminderStartDate(date)

            delegate: Item {
                id: reminderDayDelegate

                required property var model

                readonly property bool inCurrentMonth: reminderDayDelegate.model.month === reminderMonthGrid.month
                readonly property bool isSelected: root.datesEqual(reminderDayDelegate.model.date, root.reminderStartDate)

                implicitWidth: 32
                implicitHeight: 26

                MouseArea {
                    anchors.fill: parent
                    onClicked: root.setReminderStartDate(reminderDayDelegate.model.date)
                }

                Rectangle {
                    anchors.centerIn: parent
                    width: 24
                    height: 24
                    radius: 12
                    color: reminderDayDelegate.isSelected ? Theme.calendarSelected
                                                          : (reminderDayDelegate.model.today ? Theme.calendarTodayBackground : "transparent")
                    border.color: reminderDayDelegate.isSelected ? Theme.calendarSelectedBorder : "transparent"
                }

                Label {
                    anchors.centerIn: parent
                    text: reminderDayDelegate.model.day
                    font.pixelSize: 10
                    font.weight: reminderDayDelegate.isSelected ? Font.Bold : Font.Normal
                    color: !reminderDayDelegate.inCurrentMonth ? Theme.textOutOfMonth
                                                               : (reminderDayDelegate.isSelected ? Theme.textOnAccent : Theme.textPrimary)
                }
            }
        }

        Label {
            Layout.fillWidth: true
            text: qsTr("Selected: %1").arg(Qt.formatDate(root.reminderStartDate, Qt.locale().dateFormat(Locale.ShortFormat)))
            font.pixelSize: 10
            color: Theme.textHint
        }

        // Status message
        Label {
            Layout.fillWidth: true
            visible:          reminderController.statusMessage.length > 0
            wrapMode:         Text.WordWrap
            text:             reminderController.statusMessage
            font.pixelSize:   10
            color:            Theme.textHint
        }

        // Hint when nothing is selected
        Label {
            Layout.fillWidth: true
            visible:          !root.hasMediaSelection
            wrapMode:         Text.WordWrap
            text:             qsTr("Select practice material for material-specific reminders.")
            font.pixelSize:   11
            color:            Theme.textHint
        }

        // Selected media labels
        Label {
            Layout.fillWidth: true
            visible:          root.guitarProLabel.length > 0
            wrapMode:         Text.WordWrap
            text:             "🎸 " + root.guitarProLabel
            font.pixelSize:   11
            color:            Theme.textSecondary
        }

        Label {
            Layout.fillWidth: true
            visible:          root.audioLabel.length > 0
            wrapMode:         Text.WordWrap
            text:             "🎵 " + root.audioLabel
            font.pixelSize:   11
            color:            Theme.textSecondary
        }

        Label {
            Layout.fillWidth: true
            visible:          root.videoLabel.length > 0
            wrapMode:         Text.WordWrap
            text:             "🎬 " + root.videoLabel
            font.pixelSize:   11
            color:            Theme.textSecondary
        }

        Label {
            Layout.fillWidth: true
            visible:          root.imageLabel.length > 0
            wrapMode:         Text.WordWrap
            text:             "🖼 " + root.imageLabel
            font.pixelSize:   11
            color:            Theme.textSecondary
        }

        Label {
            Layout.fillWidth: true
            visible:          root.documentLabel.length > 0
            wrapMode:         Text.WordWrap
            text:             "📄 " + root.documentLabel
            font.pixelSize:   11
            color:            Theme.textSecondary
        }

        // Existing reminders list
        ScrollView {
            id: reminderScroll
            Layout.fillWidth:  true
            Layout.fillHeight: true
            clip:              true
            ScrollBar.vertical.policy: ScrollBar.AsNeeded

            ColumnLayout {
                width:   reminderScroll.availableWidth
                spacing: 8

                Repeater {
                    model: reminderController.songReminders

                    delegate: Rectangle {
                        id: reminderDelegate

                        required property int    index
                        required property int    reminderId
                        required property string title
                        required property string scheduleLabel
                        required property bool   isActive
                        required property bool   hasCondition
                        required property int    conditionStartBar
                        required property int    conditionEndBar
                        required property int    conditionMinBpm
                        required property int    conditionMinMinutes

                        Layout.fillWidth:  true
                        implicitHeight:    reminderColumn.implicitHeight + 10
                        radius:            6
                        color:             Theme.cardBackground
                        border.color:      reminderDelegate.isActive ? Theme.borderActive : Theme.borderSubtle

                        ColumnLayout {
                            id: reminderColumn
                            anchors.fill:    parent
                            anchors.margins: 6
                            spacing:         2

                            Label {
                                Layout.fillWidth: true
                                text:          reminderDelegate.title.length > 0
                                               ? reminderDelegate.title
                                               : reminderDelegate.scheduleLabel
                                font.pixelSize: 11
                                font.weight:   Font.DemiBold
                                color:         Theme.textPrimary
                                wrapMode:      Text.WordWrap
                            }

                            Label {
                                Layout.fillWidth: true
                                text:          reminderDelegate.scheduleLabel +
                                               (reminderDelegate.isActive ? "" : qsTr(" (inactive)"))
                                font.pixelSize: 10
                                color:         Theme.textTertiary
                            }

                            RowLayout {
                                Layout.fillWidth: true
                                spacing: 4

                                Button {
                                    text:           qsTr("Edit")
                                    flat:           true
                                    font.pixelSize: 10
                                    onClicked: {
                                        root.loadReminderForEdit(reminderDelegate.reminderId);
                                    }
                                }

                                Button {
                                    text:           qsTr("Delete")
                                    flat:           true
                                    font.pixelSize: 10
                                    onClicked: {
                                        reminderController.deleteReminder(reminderDelegate.reminderId);
                                        if (root.editingReminderId === reminderDelegate.reminderId)
                                        root.editingReminderId = 0;
                                    }
                                }
                            }
                        }
                    }
                }

                // ── New / edit reminder form ──────────────────────────────
                Label {
                    text:           root.editingReminderId > 0 ? qsTr("Edit") : qsTr("New")
                    font.pixelSize: 12
                    font.weight:    Font.DemiBold
                    color:          Theme.accentLight
                }

                // Auto-update title when bars/bpm change
                Connections {
                    target: condStartBar
                    function onValueChanged() { root._maybeSetAutoTitle() }
                }
                Connections {
                    target: condEndBar
                    function onValueChanged() { root._maybeSetAutoTitle() }
                }
                Connections {
                    target: condMinBpm
                    function onValueChanged() { root._maybeSetAutoTitle() }
                }

                DarkTextField {
                    id:             titleField
                    Layout.fillWidth: true
                    placeholderText: qsTr("Title (optional)")
                    font.pixelSize: 12
                    onTextEdited: root._titleIsAutoGenerated = false
                }

                ComboBox {
                    id:             scheduleCombo
                    Layout.fillWidth: true
                    font.pixelSize: 11
                    model: [
                        { label: qsTr("Once"),        value: "once"     },
                        { label: qsTr("Daily"),       value: "daily"    },
                        { label: qsTr("Weekly"),       value: "weekly"   },
                        { label: qsTr("Monthly"),      value: "monthly"  },
                        { label: qsTr("Every N days"),  value: "interval" }
                    ]
                    textRole:  "label"
                    valueRole: "value"
                }

                RowLayout {
                    id: weekdayRow
                    Layout.fillWidth: true
                    spacing: 2

                    property int selectedWeekday: root.weekdayIndexFromDate(root.reminderStartDate)

                    Label {
                        text: qsTr("Weekday")
                        color: Theme.textTertiary
                        font.pixelSize: 10
                    }

                    Repeater {
                        model: [
                            qsTr("Su"), qsTr("Mo"), qsTr("Tu"), qsTr("We"),
                            qsTr("Th"), qsTr("Fr"), qsTr("Sa")
                        ]

                        delegate: ToolButton {
                            required property int index
                            required property string modelData

                            text: modelData
                            checkable: true
                            checked: weekdayRow.selectedWeekday === index
                            font.pixelSize: 9
                            onClicked: weekdayRow.selectedWeekday = index
                        }
                    }
                }

                RowLayout {
                    Layout.fillWidth: true
                    spacing: 6
                    visible: scheduleCombo.model[scheduleCombo.currentIndex].value === "interval"

                    Label {
                        text: qsTr("Every")
                        color: Theme.textTertiary
                        font.pixelSize: 10
                    }

                    DarkSpinBox {
                        id: intervalDaysSpin
                        from: 1
                        to: 365
                        value: 2
                        Layout.fillWidth: true
                    }

                    Label {
                        text: qsTr("days")
                        color: Theme.textTertiary
                        font.pixelSize: 10
                    }
                }

                CheckBox {
                    id:             activeCheck
                    text:           qsTr("Active")
                    checked:        true
                    font.pixelSize: 11
                }

                GridLayout {
                    Layout.fillWidth: true
                    columns:      2
                    rowSpacing:   4
                    columnSpacing: 6

                    Label { text: qsTr("Bar from");  color: Theme.textTertiary; font.pixelSize: 10 }
                    DarkSpinBox { id: condStartBar;  from: 0; to: 999; Layout.fillWidth: true }

                    Label { text: qsTr("Bar to");  color: Theme.textTertiary; font.pixelSize: 10 }
                    DarkSpinBox { id: condEndBar;    from: 0; to: 999; Layout.fillWidth: true }

                    Label { text: qsTr("Min. BPM");  color: Theme.textTertiary; font.pixelSize: 10 }
                    DarkSpinBox { id: condMinBpm;    from: 0; to: 400; Layout.fillWidth: true }

                    Label { text: qsTr("Min. duration"); color: Theme.textTertiary; font.pixelSize: 10 }
                    DarkSpinBox { id: condMinMinutes; from: 0; to: 240; Layout.fillWidth: true }
                }

                Button {
                    Layout.fillWidth: true
                    text:        root.editingReminderId > 0 ? qsTr("Save") : qsTr("Add")
                    highlighted: true
                    enabled:     root.conditionInputValid && (
                                     root.editingReminderId > 0 ||
                                     root.practiceAssetId   > 0 ||
                                     root.hasMediaSelection
                                     )

                    onClicked: {
                        const date     = root.reminderDateForSave();
                        const schedule = scheduleCombo.model[scheduleCombo.currentIndex].value;
                        const title    = titleField.text.trim().length > 0
                        ? titleField.text.trim()
                        : root._buildAutoTitle();
                        const intervalDays = intervalDaysSpin.value;
                        const weekday      = weekdayRow.selectedWeekday;

                        let ok = false;
                        if (root.editingReminderId > 0) {
                            ok = reminderController.updateReminder(
                                root.editingReminderId, title, date, schedule, activeCheck.checked,
                                intervalDays, weekday);
                            if (ok)
                            reminderController.saveCondition(
                                root.editingReminderId,
                                condStartBar.value, condEndBar.value,
                                condMinBpm.value,   condMinMinutes.value);
                        } else {
                            root.commitAssetRequested();
                            ok = reminderController.createReminder(
                                title, date, schedule, activeCheck.checked,
                                condStartBar.value, condEndBar.value,
                                condMinBpm.value,   condMinMinutes.value,
                                intervalDays, weekday);
                        }

                        if (ok) {
                            root.editingReminderId = 0;
                            titleField.clear();
                            condMinMinutes.value = 0;
                            root._titleIsAutoGenerated = true;
                            root.resetReminderStartDate();
                            weekdayRow.selectedWeekday = root.weekdayIndexFromDate(root.reminderStartDate);
                            root.applyTrainingDefaults();
                        }
                    }
                }

                CheckBox {
                    Layout.fillWidth: true
                    text:           qsTr("Reminder active")
                    checked:        root.panelEnabled
                    font.pixelSize: 10
                    onToggled: {
                        root.savePanelEnabled(checked);
                        if (!checked)
                        root.saveExpanded(false);
                    }
                }
            }
        }
    }
}
